package main;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 * Provides utility methods for scaling images.
 */
public class UtilityTool {
    /** Scaled image generated by utility methods. */
	public BufferedImage scaledImage;
    /** Graphics context used for image manipulation. */
	public Graphics2D g2;
	/**
     * Constructs a UtilityTool object with a null scaled image and graphics context.
     */
	public UtilityTool() {
		this.scaledImage=null;
		this.g2=null;
	}
	/**
     * Scales the provided image to the given width and height.
     * 
     * @param original The original image to be scaled.
     * @param width The width of the scaled image.
     * @param height The height of the scaled image.
     * @return The scaled image.
     */
    public BufferedImage scaleImage(BufferedImage original, int width, int height) {
        if (original == null ||width <= 0 || height <= 0) {
            return null;
        }

        BufferedImage scaledImage = new BufferedImage(width, height, original.getType());
        Graphics2D g2 = scaledImage.createGraphics();
        g2.drawImage(original, 0, 0, width, height, null);
        g2.dispose();
        return scaledImage;
    }   

}